### ISSUE TITLE
EPIC: Admin / Account management

### ISSUE THREAD

**Issue by vivignutz** [vivignutz/berlin_bestbeers#34]

**Comment by vivignutz** [comment]
- [ ]

**Comment by vivignutz** [comment]
As a **Site Admin** I can **manage my blog** so that **it will have high quality content for all users**
As a **Site User** I can **register an account** so that I can **enjoy the blog features**

### Tasks
- [ ] USER STORY: Account registration / login #35
- [ ] USER STORY: Manage all posts #7 
- [ ] USER STORY: Create drafts #32 
- [ ] USER STORY: Approve comments #33
